services:
  - type: web
    name: apipra-service
    plan: free
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Host=db.icnzyalprjcuvbodkdwj.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=Lepilina12345678!
